# Reference: https://cloud.google.com/cloud-build/docs/build-config

steps:
  - name: 'nixos/nix:2.2.1'
    id: build_docker_image
    waitFor: ['-']
    timeout: 20m
    entrypoint: 'sh'
    args: ['.ci/build_docker_image.sh']

  - name: 'gcr.io/oak-ci/oak-hardware'
    id: run_makefile
    waitFor: ['build_docker_image']
    timeout: 20m
    entrypoint: 'make'

  # # TODO: Push docker image on merge to master

timeout: 1h

options:
  # See: https://cloud.google.com/cloud-build/docs/api/reference/rest/Shared.Types/MachineType
  machineType: 'N1_HIGHCPU_32'
  requestedVerifyOption: 'VERIFIED'
  sourceProvenanceHash: ['SHA256']
