# Reference: https://cloud.google.com/cloud-build/docs/build-config

steps:
  - name: 'nixos/nix:2.3.4'
    id: cache_dependencies
    waitFor: ['-']
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--run', 'echo "Done."']
    volumes:
    - name: nix-store
      path: /nix/

  - name: 'nixos/nix:2.3.4'
    id: run_makefile
    waitFor: ['cache_dependencies']
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--run', 'git init; make']
    volumes:
    - name: nix-store
      path: /nix/

timeout: 30m

options:
  # See: https://cloud.google.com/cloud-build/docs/api/reference/rest/Shared.Types/MachineType
  machineType: 'N1_HIGHCPU_32'
  requestedVerifyOption: 'VERIFIED'
  sourceProvenanceHash: ['SHA256']
